apiVersion: v1
kind: service
metadata: 
    name: prova-webapp-svc
    labels:
        app: prova-webapp
spec:
    type: NodePort
    ports:
        -port: 80
        nodePort: 8000
    selector:
        app: prova-webapp