apiVersion: v1
kind: deployment
metadata: 
    name: prova-webapp
spec: 
    replicas: 1
    selector: 
        matchLabels:
            app: prova-webapp
    template: 
        metadata:
            labels:
                app: prova-webapp
        spec:
            cotainers:
                -name: prova-webapp
                image: mcapurrollado/prova1:latest
                ports:
                    -containerPort: 80
